// @ts-nocheck
"use client";

import { motion } from "motion/react";

interface CoderabbitAiFeature5Props {
  mode?: "light" | "dark";
}

const CheckIcon = () => (
  <svg className="h-5 w-5 text-[#2DD4BF]" fill="none" viewBox="0 0 24 24" stroke="currentColor">
    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
  </svg>
);

export default function CoderabbitAiFeature5({
  mode = "dark",
}: CoderabbitAiFeature5Props) {
  const features = [
    "Autogenerated release notes, daily standup reports, and sprint reviews.",
    "Pull request summaries & sequence diagrams.",
    "Linear & Jira issue validation.",
  ];

  return (
    <section className="relative w-full bg-black py-16">
      <div className="mx-auto max-w-7xl px-6">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="rounded-3xl bg-zinc-900 p-8 md:p-12"
        >
          <div className="grid grid-cols-1 gap-8 lg:grid-cols-2 items-center">
            {/* Image/Chart Preview */}
            <div className="relative">
              <div className="rounded-2xl bg-pink-100 p-6 overflow-hidden">
                {/* Abstract colorful background */}
                <div className="absolute -right-20 -top-20 h-40 w-40 rounded-full bg-gradient-to-br from-orange-400 to-pink-400 opacity-60 blur-2xl" />
                <div className="absolute -left-10 bottom-0 h-32 w-32 rounded-full bg-gradient-to-tr from-cyan-400 to-yellow-400 opacity-60 blur-2xl" />

                {/* Chart Card */}
                <div className="relative rounded-xl bg-zinc-900 p-6">
                  <div className="mb-4 text-sm font-medium text-white">Smart reports</div>

                  {/* Bar Chart */}
                  <div className="flex items-end justify-between gap-2 h-40">
                    <div className="flex flex-col items-center gap-1">
                      <div className="w-8 rounded-t bg-yellow-400" style={{ height: "60%" }} />
                      <div className="w-8 rounded-b bg-yellow-300" style={{ height: "30%" }} />
                    </div>
                    <div className="flex flex-col items-center gap-1">
                      <div className="w-8 rounded-t bg-pink-400" style={{ height: "80%" }} />
                      <div className="w-8 rounded-b bg-pink-300" style={{ height: "40%" }} />
                    </div>
                    <div className="flex flex-col items-center gap-1">
                      <div className="w-8 rounded-t bg-purple-400" style={{ height: "50%" }} />
                      <div className="w-8 rounded-b bg-purple-300" style={{ height: "60%" }} />
                    </div>
                    <div className="flex flex-col items-center gap-1">
                      <div className="w-8 rounded-t bg-cyan-400" style={{ height: "70%" }} />
                      <div className="w-8 rounded-b bg-cyan-300" style={{ height: "45%" }} />
                    </div>
                  </div>

                  {/* Progress bar */}
                  <div className="mt-4 h-2 w-full rounded-full bg-zinc-800">
                    <div className="h-full w-3/4 rounded-full bg-gradient-to-r from-cyan-400 via-pink-400 to-yellow-400" />
                  </div>
                </div>
              </div>
            </div>

            {/* Content */}
            <div>
              <h2 className="text-3xl font-bold text-white md:text-4xl">
                Ship code. Get<br />automated reports
              </h2>

              <ul className="mt-8 space-y-4">
                {features.map((feature, index) => (
                  <li key={index} className="flex items-start gap-3">
                    <CheckIcon />
                    <span className="text-zinc-300">{feature}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </motion.div>
      </div>
    </section>
  );
}